<?php

/**
 * Restaurant Migration
 *
 * This migration creates the 'restaurants' table which represents the core restaurant entities
 * in the system. It contains only essential identifying information, with related data stored
 * in separate tables.
 *
 * Columns:
 * - id (bigint): Auto-incrementing primary key
 * - name (string): Business/Brand name of the restaurant
 * - description (text): Optional detailed description of the restaurant
 * - status (enum): Current operational status ['active', 'inactive', 'suspended']
 * - created_at (timestamp): When the record was created
 * - updated_at (timestamp): When the record was last updated
 * - deleted_at (timestamp): Soft delete timestamp
 *
 * Indexes:
 * - Primary Key on id
 * - Index on status for status-based queries
 * - Index on created_at for chronological queries
 *
 * @package IRMA
 * @subpackage Database\Migrations
 * @category Core
 * @author Generated by IRMA System
 * @since 1.0.0
 */

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     * 
     * Creates the restaurants table with essential fields.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('restaurants', function (Blueprint $table) {
            $table->ulid("id")->primary()->unique();
            $table->string('name')->comment('Business/Brand name of the restaurant');
            $table->text('description')
                ->nullable()
                ->comment('General description of the restaurant');
            $table->enum('status', ['active', 'inactive', 'suspended'])
                ->default('active')
                ->comment('Current operational status of the restaurant');
            $table->timestamps();
            $table->softDeletes();

            $table->index('status', 'idx_restaurant_status');
            $table->index('created_at', 'idx_restaurant_created');
        });
    }

    /**
     * Reverse the migrations.
     * 
     * Drops the restaurants table.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('restaurants');
    }
};
